# Site settings
name: EdgeZero AI site
title: EdgeZero AI
url: http://www.edgezero.in
description: "Powering the world without consuming power... Well almost!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: EdgeZero AI, India

# Build settings
markdown: kramdown
permalink: pretty

